template_type: TF
terraform_version: 0.12
terraform_012_parameters:
  - root_module: AWS-Templates/terraform12novariablemodule
  - root_module: AWS-Templates/dynamic-blocks-and-splat-expressions
  - root_module: AWS-Templates/first-class-expressions
  - root_module: AWS-Templates/for-each-for-resources
  - root_module: AWS-Templates/for-expressions




